---
abstract: 'BSD utilities written in pure Perl'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlPowerTools
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=PerlPowerTools
  repository: git://github.com/briandfoy/PerlPowerTools.git
version: 1.003
